#! /usr/bin/perl

use 5.010;

my @numbers = qw( 1 3 5 7 9 );

#print "total is :",&total( @numbers) ;

sub total {
 my $sum = 0;
 foreach my $n (@_){
     print "this is $n\n";
     $sum += $n;
 }
 $sum;
} 

print "total is :",total( @numbers),"\n" ;
print "total is :",total( @numbers),"\n";
print "Enter some numbers on separate lines:\n";
chomp(my @ns=<STDIN>);
print "The total of those numbers @ns, is:",total(@ns),"\n";
