#! /usr/bin/perl

use 5.010;


sub my_average{
  my @ary = @_;
  #print "total numbers:",($#ary+1),"\n";
  #print &total(@_) ;
  &total(@_)/($#ary+1) ;
}

sub total {
 my $sum = 0;
 foreach my $n (@_){
     $sum += $n;
 }
 $sum;
} 

sub above_average{
    my $average= &my_average(@_);
    my @ary = ();
    foreach my $n (@_){
       if($n> $average){
          push @ary,$n ;
       }
    }
    @ary;
}

my @fred = above_average(1..10);
print "\@fred is @fred\n";
print "(Should be 6,7,8,9,10)\n";
my @barney = above_average(100,1..10);
print "\@barney is @barney\n";
print "(Should be just 100)\n";
